name: Synopsys Security Testing

on:
  pull_request:
    branches: [ main ]
  
env:
  DETECT_PROJECT_NAME: pgreen_ghaction_test
  DETECT_PROJECT_VERSION_NAME: main
  DETECT_TOOLS: DETECTOR
  DETECT_TIMEOUT: 3000
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: install dependency
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    - run: npm install --no-audit --no-fund --silent
    - name: Black Duck PR Scan
      if: ${{ github.event_name == 'pull_request' }}
      uses: synopsys-sig/synopsys-action@v1.2.0
      env:
        DETECT_EXCLUDED_DETECTOR_TYPES: GIT
      with:
        include_diagnostics: true
        blackduck_url: ${{ secrets.BLACKDUCK_URL }}
        blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
        blackduck_scan_full: false
        blackduck_automation_prcomment: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

